# Adapted from https://packaging.python.org/guides/supporting-windows-using-appveyor/

skip_non_tags: false  # we want to build untagged revisions.
image: "Visual Studio 2019"

version: "{branch}.{build}"  # Makes build version information more readable on appveyor

environment:
  PIP_EXTRA_INDEX_URL: "http://pypi.naturalcapitalproject.org/simple/"
  PIP_TRUSTED_HOST: "pypi.naturalcapitalproject.org"
  PIP_PREFER_BINARY: 1
  PIP_INSTALL: "pip install"
  PYTHON_DIR: "C:\\Python37-x64"

install:
    - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"
    - "python --version"
    -
    # We need wheel installed to build wheels
    - "python -m pip install wheel numpy cython setuptools_scm"
    - "python -m pip install -r requirements.txt -r requirements-dev.txt"

    # Need to copy some files around to get the build to work as expected
    - copy /B /Y "%PYTHON_DIR%\Lib\site-packages\shapely\DLLs\geos_c.dll" "%PYTHON_DIR%\Lib\site-packages\shapely\DLLs\geos.dll"

    # Install helper tools
    - choco install make zip
    - curl -o gcloud-sdk.zip https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-261.0.0-windows-x86_64-bundled-python.zip
    - unzip -q gcloud-sdk.zip

build_script:
  - make binaries

test_script:
    - echo "Nothing to see here :)"

# only run these commands on build/test success
on_success:
    - "python exe\\write_service_account_key.py --no-crash GOOGLE_SERVICE_ACC_KEY client_secret.json"
    - "if exist client_secret.json .\\google-cloud-sdk\\bin\\gcloud auth activate-service-account --key-file=client_secret.json"
    - "if exist client_secret.json make GSUTIL='%CD%\\google-cloud-sdk\\bin\\gsutil.cmd' deploy"

artifacts:
    - path: dist\*
