channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - make
    - pandas
    - numexpr>=2.4.6
    - nomkl
    - numpy
    - cvxpy
    - pyside2
    - qtpy
    - qtawesome
    - Shapely
    - requests
    - pygeoprocessing
    - pyinstaller==4.1
    - setuptools
    - toml
    - setuptools_scm
    - psutil
    - cython
    - wheel
    - rtree>=0.8.2,!=0.9.1,<=0.9.4  # For pyinstaller compatibility.  See natcap/invest#439
    - pip
    - 7zip
    - pip:
        - natcap.invest>=3.9
