name: root-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - make
    - pandas
    - numexpr>=2.4.6
    - numpy
    - scipy
    - cvxpy
    - pyside2
    - qtpy
    - qtawesome
    - Shapely
    - requests
    - pygeoprocessing
    - pyinstaller==3.5
    - setuptools_scm
    - cython
    - wheel
    - rtree>=0.8.2,!=0.9.1,<=0.9.4  # For pyinstaller compatibility.  See natcap/invest#439
    - pip:
        - natcap.invest>=3.9
