name: env
channels:
    - conda-forge
    - defaults
dependencies:
    - make
    - pandas
    - numexpr>=2.4.6
    - numpy
    - scipy
    - cvxpy
    - pyside2
    - qtpy
    - qtawesome
    - Shapely
    - requests
    - pygeoprocessing
    - pyinstaller==3.5
    - setuptools_scm
    - cython
    - wheel
    - pip:
        - natcap.invest>=3.9
